defaults: &defaults
  adapter: postgresql
  encoding: unicode
  reconnect: true
  min_messages: warning
  pool: 15
  timeout: 5000

development:
  <<: *defaults
  database: wedding_development
  username: solucao_social
  password: solucao_social

test:
  <<: *defaults
  database: wedding_test
  username: solucao_social
  password: solucao_social

production:
  <<: *defaults
  database: wedding_production
  username: solucao_social
  password: solucao_social
